### ISSUE TITLE
adding new item results in: json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by Fe3lApAcUt** [project-alice-assistant/skill_BringShoppingList#9]
Hey

tried to add an item on latest branch 1.0.0-b1 and got the following error. Maybe {locale} is not accessible? 

```
2020-04-03 16:58:57,883 [Thread-1] - [ERROR] - [SkillManager]            Error dispatching message to BringShoppingList: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/home/pi/ProjectAlice/core/base/SkillManager.py", line 278, in dispatchMessage
    consumed = skillInstance.onMessageDispatch(session)
  File "/home/pi/ProjectAlice/core/base/model/AliceSkill.py", line 425, in onMessageDispatch
    ret = function(session=session)
  File "/home/pi/ProjectAlice/core/util/Decorators.py", line 147, in exceptionDecorator
    return func(*args, **kwargs)
  File "/home/pi/ProjectAlice/core/util/Decorators.py", line 127, in offlineDecorator
    return func(*args, **kwargs)
  File "/home/pi/ProjectAlice/skills/BringShoppingList/BringShoppingList.py", line 159, in addItemIntent
    added, exist = self._addItemInt(items)
  File "/home/pi/ProjectAlice/skills/BringShoppingList/BringShoppingList.py", line 64, in _addItemInt
    bringItems = self.bring().get_items(self.LanguageManager.activeLanguageAndCountryCode)['purchase']
  File "/home/pi/ProjectAlice/venv/lib/python3.7/site-packages/BringApi/BringApi.py", line 69, in get_items
    transl = BringApi.loadTranslations(locale)
  File "/home/pi/ProjectAlice/venv/lib/python3.7/site-packages/BringApi/BringApi.py", line 136, in loadTranslations
    cls._translations = requests.get(f'https://web.getbring.com/locale/articles.{locale}.json').json()
  File "/home/pi/ProjectAlice/venv/lib/python3.7/site-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

Regards,
Marcel

**Comment by Fe3lApAcUt** [comment]
Closing here, re-opened in the right section: https://github.com/project-alice-assistant/ProjectAliceSkills/issues/115
